# apiVersion: v1
# kind: Service
# metadata:
#   name: mongodb-service
#   namespace: exam
# spec:
#   ports:
#     - port: 27017
#       targetPort: 27017  # Added targetPort for clarity
#       protocol: TCP
#   selector:
#     app: mongodb
#   type: ClusterIP
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: firstvolume-pv  # Modified to follow naming conventions
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 2Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: firstvolume-claim  # Modified to follow naming conventions
#   namespace: exam
#   labels:
#     app: mongodb
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mongodb-deployment
#   namespace: exam
#   labels:
#     app: mongodb
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: mongodb
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       name: mongodb
#       labels:
#         app: mongodb
#     spec:
#       containers:
#         - name: mongodb-container  # Changed the container name for clarity
#           image: mongo:latest
#           resources: {}
#           livenessProbe:
#             tcpSocket:
#               port: 27017
#             initialDelaySeconds: 15
#             periodSeconds: 20
#           readinessProbe:
#             tcpSocket:
#               port: 27017
#             initialDelaySeconds: 5
#             periodSeconds: 10
#           startupProbe:
#             tcpSocket:
#               port: 27017
#             periodSeconds: 10
#             failureThreshold: 3
#           ports:
#             - containerPort: 27017
#               name: mongodb-port
#           volumeMounts:
#             - name: firstvolume  # Changed volume name to match the PersistentVolumeClaim
#               mountPath: /var/lib/docker/volumes/firstVolume/_data
#       volumes:
#         - name: firstvolume  # Changed volume name to match the PersistentVolumeClaim
#           persistentVolumeClaim:
#             claimName: firstvolume-claim  # Changed to match the PersistentVolumeClaim
